export interface IUser {
    id?: string;
    fName?: string;
    lName?: string;
    OtherName?: string;
    jobTitle?: string;
    status?: boolean;
    userStatus?: string;
    address?: string;
    email?: string;
    password?: string;
    phoneNumber?: string;
    phoneNumber1?: string;
    licenceNumber?: string;
    licenceClass?: string;
    licenceIssueDate?: Date;
    licenceExpDate?: Date;
    FMT?: Date;
    LME?: Date;
    MRWAHVACertification?: Date;
    profileImageUrl?: string;
    imageName?: string;
    emergencyContact?: string;
    clientID?: string;
    lastMessage?: string;
    lastMessageTime?: any;
    currentLocation?: any;
    dutyStatus?: string;
    lastJobId?:string;
    information?:string;
}

export class User implements IUser {
    $key?: string;
    fName?: string;
    lName?: string;
    OtherName?: string;
    displayName?: string;
    jobTitle?: string;
    status?: boolean;
    userStatus?: string;
    address?: string;
    email?: string;
    password?:string;
    phoneNumber?: string;
    phoneNumber1?: string;
    licenceNumber?: string;
    licenceClass?: string;
    licenceIssueDate?: Date;
    licenceExpDate?: Date;
    FMT?: Date;
    LME?: Date;
    MRWAHVACertification?: Date;
    profileImageUrl?: string;
    imageName?: string;
    emergencyContact?: string;
    lastMessage?: string;
    lastMessageTime?: Date;
    currentLocation?: any;
    dutyStatus?: string;
    lastJobId?:string;
    information?:string;
    constructor(data: IUser, id?) {
        this.$key = data.id?data.id:id;
        this.fName = data.fName;
        this.lName = data.lName;
        this.OtherName = data.OtherName;
        this.displayName = data.fName + ' ' + data.lName;
        this.jobTitle = data.jobTitle;
        this.status = data.status;
        this.address = data.address;
        this.email = data.email;
        this.password = data.password;
        this.phoneNumber = data.phoneNumber;
        this.phoneNumber1 = data.phoneNumber1;
        this.licenceNumber = data.licenceNumber;
        this.licenceClass = data.licenceClass;
        this.licenceIssueDate = data.licenceIssueDate;
        this.licenceExpDate = data.licenceExpDate;
        this.FMT = data.FMT;
        this.LME = data.LME;
        this.MRWAHVACertification = data.MRWAHVACertification;
        this.profileImageUrl = data.profileImageUrl;
        this.imageName = data.imageName;
        this.emergencyContact = data.emergencyContact;
        this.lastMessage = data.lastMessage;
        this.lastMessageTime = data.lastMessageTime.toDate();
        this.dutyStatus = data.dutyStatus;
        this.currentLocation = data.currentLocation;
        this.userStatus = data.userStatus;
        this.lastJobId = data.lastJobId;
        this.information = data.information;
    }
}
